name: 📝 Documentation Fix
description: Point out an error or suggest a change in the documentation.
title: "[DOCS]:"
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the Mautic Community Handbook! Please fill out the details below so we can fix it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe what is inaccurate, missing, or confusing in the documentation.
      placeholder: "e.g., The example code on page X is out of date and no longer works."
    validations:
      required: true
  
  - type: textarea
    id: doc-link
    attributes:
      label: Relevant Documentation URL
      description: Please provide a link to the exact documentation page that needs to be updated.
      placeholder: "e.g., https://contribute.mautic.org/page-to-fix"

  - type: dropdown
    id: willingness-to-pr
    attributes:
      label: Are you willing to help us fix this by making a pull request?
      description: Contributing a pull request is the fastest way to get this fixed.
      options:
        - "— Select an option —"
        - "No"
        - "Yes"
        - "Yes, but I need help"
    validations:
      required: true
  
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions (Optional)
      description: How do you suggest the documentation could be fixed or improved?
      placeholder: "e.g., I think changing the example code to this would solve the issue..."

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recordings (Optional)
      description: To help us understand the issue visually, please attach any relevant images or recordings.
      placeholder: "Drag and drop the files here."