name: 🌱 Feature Request
description: Request a new feature or enhancement.
title: "[FEAT]:"
labels: ["enhancement", "blocked"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the details below to help us understand and prioritize it.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the feature you would like to see.
      placeholder: "e.g., I'd like to be able to upload multiple files at once. This would be useful because..."
    validations:
      required: true
  
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions (Optional)
      description: How do you suggest this feature should be implemented?
      placeholder: "e.g., A user could press the CTRL key while selecting files to choose more than one."