name: Linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-22.04 # See https://github.com/errata-ai/vale-action/issues/128 before upgrading
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt

    - name: Reviewdog
      on: [pull_request]
        jobs:
          reviewdog:
            name: reviewdog
            runs-on: ubuntu-latest
            steps:
              # ...
              - uses: reviewdog/action-setup@v1
                with:
                  reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
              - name: Run reviewdog
                env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                 reviewdog -f=golint -diff="git diff FETCH_HEAD" -reporter=github-pr-check -runners=golint,govet

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt
    
    - name: Build docs
      working-directory: docs
      run: make html

    - name: Check links
      working-directory: docs
      run: make checklinks
